# Generated by Django 4.2.4 on 2023-09-10 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_id', models.PositiveIntegerField()),
                ('Booking_date', models.DateTimeField(auto_now_add=True)),
                ('Num_of_tickets', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_id', models.PositiveIntegerField()),
                ('Bus_name', models.CharField(max_length=255)),
                ('Total_seats', models.PositiveIntegerField()),
                ('Bus_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schedule_id', models.PositiveIntegerField()),
                ('Departure_time', models.DateTimeField()),
                ('Arrival_time', models.DateTimeField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Available_seats', models.PositiveIntegerField()),
                ('Bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flim.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operator_id', models.PositiveIntegerField()),
                ('Operator_name', models.CharField(max_length=255)),
                ('Contact_number', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Route_id', models.PositiveIntegerField()),
                ('Source_city', models.CharField(max_length=255)),
                ('Destination_city', models.CharField(max_length=255)),
                ('Distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reservation_id', models.PositiveIntegerField()),
                ('Seat_number', models.PositiveIntegerField()),
                ('Is_reserved', models.BooleanField(default=False)),
                ('Schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flim.busschedule')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAndRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review_id', models.PositiveIntegerField()),
                ('Rating', models.PositiveIntegerField()),
                ('Review_text', models.TextField()),
                ('Review_date', models.DateTimeField(auto_now_add=True)),
                ('Bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flim.bus')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_id', models.PositiveIntegerField()),
                ('Payment_date', models.DateTimeField(auto_now_add=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Payment_status', models.CharField(max_length=255)),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flim.booking')),
            ],
        ),
        migrations.AddField(
            model_name='busschedule',
            name='Route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flim.route'),
        ),
        migrations.AddField(
            model_name='bus',
            name='Operator_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flim.operator'),
        ),
        migrations.AddField(
            model_name='booking',
            name='Schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flim.busschedule'),
        ),
        migrations.AddField(
            model_name='booking',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
