# Generated by Django 4.2.4 on 2023-09-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='User',
            field=models.IntegerField(),
        ),
    ]
