# Generated by Django 4.0.3 on 2023-09-14 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flim', '0004_rename_num_of_tickets_booking_no_of_tickets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Booking',
            new_name='Booking_id',
        ),
        migrations.RenameField(
            model_name='reviewandrating',
            old_name='Bus',
            new_name='Bus_id',
        ),
        migrations.RenameField(
            model_name='seatreservation',
            old_name='Schedule',
            new_name='Schedule_id',
        ),
        migrations.RemoveField(
            model_name='reviewandrating',
            name='Review_id',
        ),
        migrations.RemoveField(
            model_name='reviewandrating',
            name='User',
        ),
        migrations.AddField(
            model_name='reviewandrating',
            name='User_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flim.booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='Arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='Departure_time',
            field=models.TimeField(),
        ),
    ]
