# Generated by Django 4.0.3 on 2023-09-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flim', '0005_rename_booking_payment_booking_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewandrating',
            name='User_id',
        ),
    ]
